### ISSUE TITLE
Client doesn't implement IConnection.Send

### ISSUE THREAD

**Issue by galensoft** [dragonslaya84/EpicOnlineTransport#1]
It seems that the Client's send hasn't been updated to be called with (ArraySegment<byte>, int)

Exact error is:
`Library\PackageCache\com.miragenet.epic@1.0.3\Transport\Client.cs(20,35): error CS0535: 'Client' does not implement interface member 'IConnection.Send(ArraySegment<byte>, int)`

**Comment by dragonslaya84** [comment]
Fixed in new version
